export const CONFIG = {
  TWITTER_API_KEY: process.env.TWITTER_API_KEY,
  TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
  TELEGRAM_CHAT_ID: process.env.TELEGRAM_CHAT_ID,
  TWITTER_USERNAME: process.env.TWITTER_USERNAME
};
